language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=`python -m site --user-base`/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test

notifications:
  email:
    on_success: never
