language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly

install:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      export ARCH='x86_64-unknown-linux-gnu';
    else
      export ARCH='x86_64-apple-darwin';
    fi
  - export DEPLOY_ARTIFACT="ruplicity-console-$TRAVIS_TAG-$ARCH.tar.gz"

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=`python -m site --user-base`/bin:$PATH

script:
  - travis-cargo build -- --release
  - travis-cargo test

after_success:
  - cp target/release/ruplicity-console ruplicity-console
  - tar -cvf - ruplicity-console LICENSE README.md | gzip > "$DEPLOY_ARTIFACT"

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "$DEPLOY_ARTIFACT"
  skip_cleanup: true
  on:
    tags: true
    TRAVIS_RUST_VERSION: 'stable'

notifications:
  email:
    on_success: never
