language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache:
  directories:
    - $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly

script:
  - travis-cargo build
  - travis-cargo test

notifications:
  email:
    on_success: never
