language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache:
  directories:
    - $HOME/.cargo

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo test

notifications:
  email:
    on_success: never
