environment:
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      MSYS_BITS: 64
      ARTIFACT: ruplicity-console-windows-mingw-amd64-$(APPVEYOR_REPO_TAG_NAME).zip
    - TARGET: i686-pc-windows-gnu
      ARTIFACT: ruplicity-console-windows-mingw-i686-$(APPVEYOR_REPO_TAG_NAME).zip
      MSYS_BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      ARTIFACT: ruplicity-console-windows-amd64-$(APPVEYOR_REPO_TAG_NAME).zip
    - TARGET: i686-pc-windows-msvc
      ARTIFACT: ruplicity-console-windows-i686-$(APPVEYOR_REPO_TAG_NAME).zip

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose --release

after_build:
  - copy target\release\ruplicity-console.exe ruplicity-console.exe
  - 7z a %ARTIFACT% ruplicity-console.exe LICENSE README.md

test_script:
  - cargo test -- --nocapture

artifacts:
  - path: $(ARTIFACT)
    name: zip

deploy:
  description: "TODO: edit description"
  provider: GitHub
  auth_token:
    secure: zVY6XhdaRF5MOWb4168ZGOB0T7KlCf+tYntycx8+8xEfQXL9RN4HuAW155AHVj9i
  artifact: zip
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    MSYS_BITS: ""
